### ISSUE TITLE
Ep04 final challenge redundancy in solution to part 4

### ISSUE THREAD

**Issue by ezherman** [carpentries-incubator/snakemake-novice-bioinformatics#10]
In part 4 of this challenge, learners are asked to re-run `kallisto_quant` on all etoh60 samples after adapting the `trimreads` rule by deleting input files. The solution is given as:

`$ rm -r trimmed/etoh60_*.fq kallisto.etoh60_*`

I obtain the requested behaviour by only deleting the files in `trimmed`, i.e.:

`$ rm trimmed/etoh60_*.fq`

Maybe I have missed something here, but it seems that deleting the kallisto files is not necessary for this question.

**Comment by tbooth** [comment]
The entire point of this question is that removing just the trimmed reads is *not* enough. I checked this just now and confirmed that on my setup the existing answer is right and you do need to remove both.

I'm not sure what you are doing differently, Ezra. Are you sure you didn't leave the `-F` or `-R` flags in the Snakemake command? Or did you touch the input files as per the answer to part 3 and not fully re-run the workflow to reset the timestamps?

**Comment by ezherman** [comment]
Ah yes, my bad! I can't reproduce the behavior, so I must have forgotten to remove a flag or to fully re-run after resetting the timestamps. Sorry Tim!
