### ISSUE TITLE
Ep 6 "Exercise - fixing Kallisto" - `2>` vs `>&`

### ISSUE THREAD

**Issue by ezherman** [carpentries-incubator/snakemake-novice-bioinformatics#12]
The introduction to the exerccise "fixing Kallisto" recommends using `>&` to capture stderr and stdout. However, the exercise solution uses `2>`, which to my understanding only captures stderr:

```
# Kallisto quantification of one sample, with log capture.
rule kallisto_quant:
    output: directory("kallisto.{sample}")
    input:
        index = "Saccharomyces_cerevisiae.R64-1-1.kallisto_index",
        fq1   = "trimmed/{sample}_1.fq",
        fq2   = "trimmed/{sample}_2.fq",
    shell:
     r"""mkdir {output}
         kallisto quant -i {input.index} -o {output} {input.fq1} {input.fq2} 2> {output}/kallisto_quant.log
      """
```

Kallisto is included in the MultiQC output when using `2>`, but it might be good to update the exercise text so it's consistent with the solution.

**Comment by tbooth** [comment]
Well spotted. I intended to stick with `>&` throughout. A grep suggests this was the only case of `2>` that I missed - the sample Snakefiles all use `>&`.
