### ISSUE TITLE
gm display on Mac OS

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries-incubator/snakemake-novice-bioinformatics#19]
In `04-the_dag` the command `snakemake -f --dag kallisto.etoh60_1/abundance.h5 | gm display -` does not work on my Mac (Big Sur 11.6.5). The `display` option is not available. I tried to google for a fix but have not been able to find one.

What I use instead is `snakemake -f --dag kallisto.etoh60_1/abundance.h5 | dot -Tpng > dag.png` and open `dag.png`. 

If there isn't a workaround for `gm display`, would adding the `dot` solution as an alternative be an idea? I could put in the PR if you'd like.

**Comment by tbooth** [comment]
Is this using the version of GraphicsMagick installed via Conda? I'm wondering if it is just a problem with this Conda package (maybe we can specify a different version?) or if it is a fundamental thing that isn't supported in Mac builds of GraphicsMagick.
