### ISSUE TITLE
Episode 06: Target rules may not contain wildcards

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries-incubator/snakemake-novice-bioinformatics#22]
I am following the lesson until the end of episode 05. My Snakefile is then identical to `ep05.Snakefile`. Then, in episode 06, I add the first proposed solution to the fastqc rule and run ` snakemake -n -j1 -p fastqc`. The output is:

```
Conditions are:  ['ref', 'etoh60', 'temp33']
Building DAG of jobs...
WorkflowError:
Target rules may not contain wildcards. Please specify concrete files or a rule without wildcards.
```

This command, though, works: `snakemake -n -j1 -p reads/ref_1_1_fastqc.html`.
Same holds for the other solutions for the fastqc rule.

I have been trying a lot of things, and even when I run `ep06.Snakefile` on a fresh folder with data (after renaming `reads/ref_1_1.fq` to `reads/ref1_1.fq`), running `snakemake -n -j1 -p` gives this error.

The only thing I noticed is that after adding the rule `all_counts` from `ep05.Snakefile` back into `ep06.Snakefile`, I can run `snakemake -n -j1 -p` again, but still not `snakemake -n -j1 -p fastqc`.

(same problem without `-n` for all of the above, which I guess makes sense).

Googling the problem gave hints (something with the first rule?) but didn't allow me to fix it. Any suggestions?

**Comment by tbooth** [comment]
I've tried to clarify this in episode 5. In episodes 1 to 4 we tell you that Snakemake must always be given a target output file (or files). In ep5 we say that you can avoid this if you make a rule with no wildcards, but then you still need to put this at the top or else tell Snakemake what rule to use to obtain its targets.

I've also added a note to the solution, and to the Snakefile itself, saying how to run it.

**Comment by lexnederbragt** [comment]
Thanks! I now understand that my problem resulted from a fundamental misunderstanding of snakemake - and a not too clear error message. I think I am now getting it!
