### ISSUE TITLE
Fasta transcriptome file is described as a fastq

### ISSUE THREAD

**Issue by mwhamgenomics** [carpentries-incubator/snakemake-novice-bioinformatics#35]
In [Chapter 6: Handling awkward programs -> Exercise - adding Salmon as an alternative to Kallisto](https://carpentries-incubator.github.io/snakemake-novice-bioinformatics/06-wrapping/index.html#exercise---adding-salmon-as-an-alternative-to-kallisto), the transcriptome file is referred to as `<transcriptome as fastq>`, even though it should be a fasta - which caught me out when I was following through the class.

**Comment by tbooth** [comment]
Well spotted, Murray. Thanks. Hope the course this week is going well in general.
