### ISSUE TITLE
Proposed rewording of challenge 2, episode 11.

### ISSUE THREAD

**Issue by ezherman** [carpentries-incubator/snakemake-novice-bioinformatics#6]
I read "Use this to discover the length of the longest contig from all these assemblies." as: take all contigs from the 12 assemblies and find the one longest contig. The answer shows that the challenge asks for the longest contig from each condition and kmer length combination, i.e. 12 max contigs.

Perhaps this could be rephrased as:

"For each combination of condition and kmer length, use this to discover the length of the longest contig. You should end up with 12 contig lengths."

**Comment by tbooth** [comment]
I've rephrased the question. Really the exact output here doesn't matter - the key thing is to get a working workflow that makes 12 assemblies. However, the final step of picking the highest number is something which not everyone on the course will know how to do, and I wouldn't want this problem to distract people. (Given there are only twelve results, picking the highest number by eye is perfectly valid, IMO)
