### ISSUE TITLE
Mention Snakemake wrappers

### ISSUE THREAD

**Issue by tbooth** [carpentries-incubator/snakemake-novice-bioinformatics#65]
from @cmeesters:

> we recommend using Snakemake wrapper to handle awkward programs to increase the stability of workflows
> wherever possible. There is not even an outlook to wrappers. This is - IMO - a major flaw.

Snakemake wrappers are available for these tools:

https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/fastqc.html
https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/kallisto.html
https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/salmon.html
https://snakemake-wrappers.readthedocs.io/en/stable/wrappers/multiqc.html

But not for the older tools velvet or fastx_toolkit.

**Comment by tbooth** [comment]
Agreed that this is a major feature that should not be ignored in the the course.

I'll add info on this feature and pointers to the docs. I still think the focus of the course here needs to be on how learners can integrate tools for themselves, as there will not be a wrapper for every situation. Also, if a wrapper is available and works then there is not much to teach - you just use it and you are done.

I'm not sure though if wrappers should be introduced in ep06 or after the Conda episode, as wrappers and Conda go hand in hand. Possibly mentioned in ep06 but covered in more detail in/after ep10

**Comment by cmeesters** [comment]
Note: I do not think that including wrappers for all tools in this particular workflow is a necessity during the course. It would be nice to have a solution which features wrappers for rules where it makes sense (not fastx, obviously).
