### ISSUE TITLE
Clearer solution for Ep08

### ISSUE THREAD

**Issue by tbooth** [carpentries-incubator/snakemake-novice-bioinformatics#69]
From @cmeesters:

> A pretty good chapter. Yet, now there cannot be a one-file solution. You ask participants to
> download the solution and split the content into different files manually. This is pretty error-prone.
> Do not do that: You will realize upon teaching, that participants will stumble and comprehension comes from seeing. 
> You need to require, that the configuration file gets into a separate folder, and you need to provide individual solutions for this.

**Comment by tbooth** [comment]
My apologies, but I don't understand what this comment is suggesting.

**Comment by cmeesters** [comment]
Essentially, the solution is a file, which embeds a Snakefile and configuration. My suggestion is, to split this into separate files. (please excuse my wording, it was odd)
